// Official Rules Content
export const officialRules = `NO PURCHASE NECESSARY TO ENTER THE SWEEPSTAKES. A PURCHASE DOES NOT INCREASE YOUR CHANCES OF WINNING.

1. Eligibility: The Corona Premier Serve Sweepstakes (the "Sweepstakes") is open only to legal U.S. residents residing in the state of California ("Eligibility Area") who are at least twenty-one (21) years old at the time of entry. Persons in any of the following categories are not eligible to participate or win a prize: (a) persons who are employees or agents of Crown Imports LLC, Administrator (as defined below), their respective parent companies, affiliates, divisions, subsidiaries, suppliers, distributors and the service agencies or independent contractors of any of the above organizations; (b) suppliers, distributors or retailers of alcohol beverage products; (c) individuals engaged in the development of, the production or distribution of materials for, or the implementation of this Sweepstakes; or (d) employees of, persons in the immediate family of (spouses, domestic partners, parents, children and siblings), or persons living in the same household as any person in any of the preceding categories. Subject to all applicable federal, state, and local laws and regulations. Void outside Eligibility Area and where prohibited. Participation constitutes entrant's full and unconditional agreement to these Official Rules and Sponsor's and Administrator's decisions, which are final and binding in all matters related to the Sweepstakes. Winning a prize is contingent upon fulfilling all requirements set forth herein.

2. Sponsor: Crown Imports LLC, 131 S. Dearborn St., Chicago, IL 60603. Administrator: Optivate Agency 4403 Oleander Dr., Ste. C #251, Wilmington, NC 28403.

3. Timing: The Sweepstakes begins on December 15, 2025 at 12:00 AM Eastern Time ("ET") and ends on February 11, 2026 at 11:59 PM ET (the "Promotion Period"). Administrator's computer is the official time-keeping device for the Sweepstakes.

4. How to Enter: There are two (2) ways to enter:

Via Website Entry. During the Promotion Period, go to cbisweeps.com/PremierServe2026Sweepstakes and follow the instructions to be entered into the Sweepstakes. Website Entries must be received by 11:59 PM ET on the last day of the Promotion Period to be eligible for inclusion in the random drawing.

Via QR Code Entry. During the Promotion Period, locate and scan the QR code on Sponsor branded advertising materials using your web-enabled wireless device equipped with a QR code reader application (downloadable for free via the Internet) to be taken to a URL and follow the instructions to be entered into the Sweepstakes. QR Code Entries must be received by 11:59 PM ET on the last day of the Promotion Period to be eligible for inclusion in the random drawing.

Limit: One (1) entry per person per calendar day. For purposes of this Sweepstakes, a "calendar day" is defined as beginning at 12:00 AM ET and ending at 11:59 PM ET on any one (1) calendar date. Any attempt by any entrant to obtain more than the stated number of entries by using multiple/different addresses, identities or registrations, or any other methods will void that entrant's entries and that entrant may be disqualified.  Entries generated by script, macro or other automated means and entries which subvert the entry process are void.   Facsimile and mechanically reproduced entries will not be accepted. Sponsor is not responsible for lost, late, incomplete, illegible, invalid, postage-due (to the extent applicable), unintelligible or misdirected entries, which will be disqualified. In the event of a dispute as to any participation, the authorized account holder of the email address or phone number used to enter will be deemed to be the entrant. The "authorized account holder" is the natural person assigned a phone number by a cellular service provider or an email address by an internet access provider, online service provider or other organization responsible for assigning email addresses for the domain associated with the submitted address. The potential winner may be required to show proof that he/she is the authorized account holder. Normal internet access and data charges imposed by your internet/wireless phone service provider may apply. See your internet/wireless provider for pricing plan details. All entries submitted will not be acknowledged or returned. Entries will not be judged but must adhere to the entry guidelines indicated herein, as determined by Sponsor/Administrator in their sole discretion.

5. Random Drawing(s): Administrator is an independent judging organization whose decisions as to the administration and operation of the Sweepstakes and the selection of the potential winner(s) are final and binding in all matters related to the Sweepstakes. Administrator will select the potential Sweepstakes winner(s) in a random drawing from all eligible entries received during the Promotion Period, on or around February 12, 2026. Odds of winning a prize depend on the number of eligible entries received during the Promotion Period. The potential winner(s) will be notified by mail, email or phone (depending on potential winners' method of Entry) on or about the first business day following the random drawing in which they were selected. Each potential winner of prizes valued at or greater than $25.00, will be required to sign and return to Sponsor/Sponsor's representative, within three (3) calendar days of the date notice or attempted notice is sent, an Affidavit of Eligibility, Liability & Publicity Release (a written "Affidavit") in order to claim his/her prize and each potential winner of prizes valued at less than $25.00, will be required immediately upon notice or attempted notice is sent to attest by telephone (which Entrant agrees may be recorded by Sponsor, Administrator or their designees) to his/her eligibility to participate in the Sweepstakes, consent to and compliance with these Official Rules (including but not limited to the Releases set forth in Sections 7 and 8 below) and all applicable regulations (an oral "Affidavit"). Noncompliance within any specified time period, return of any prize or prize notification as undeliverable, or declining a prize for any reason, will result in disqualification without further notice and an alternate winner may be selected in a random drawing from among all remaining eligible entries received.  Potential winner must continue to comply with all terms and conditions of these Official Rules and winning is contingent upon fulfilling all requirements.

6. Prizes & Approximate Retail Values ("ARVs"):

One (1) GRAND PRIZE(S):

Grand Prize shall consist of two (2) Courtside Box Seats for winner and one (1) guest to the BNP Paribas Open Tennis Tournament in Indian Wells, CA (the "Event") for Saturday, March 07, 2026 and Sunday, March 08, 2026, Day and Evening Sessions, Valet Parking for each day, one (1) Corona Premier-branded 54 qt. Hard Cooler, one (1) Corona Premier-branded Blue Tees Speaker and one (1) $200 Sponsor-specified gift card. ARV of Grand Prize: $4770 total.

One (1) FIRST PRIZE:

First Prize shall consist of two (2) Box Seats for winner and one (1) guest to the Event for Tuesday, March 10, 2026, Day and Evening Sessions, VIP Parking, and one (1) Corona Premier-branded 54 qt. Hard Cooler.  ARV of First Prize:  $1810 total.

Tickets are subject to availability, venue capacity, age, and other restrictions. Selection of Event seat locations is in Sponsor's sole discretion. If winner is unable or unwilling to attend Event on the date or in the location selected, the prize will be forfeited and may be awarded to an alternate winner. Each prize winner and guest are solely responsible for all other travel expenses not specifically set forth herein, including but not limited to meals, incidentals, lodging, surcharges, service charges, personal charges, security fees, shipping and handling, taxes, transportation (ground and airfare), travel and other insurance, souvenirs and other incidentals and items of a personal nature. DO NOT ENTER THE SWEEPSTAKES IF YOU ARE NOT PREPARED TO PAY FOR LODGING AND TRAVEL TO/FROM THE EVENT. Winner's guest to the Event must be twenty-one (21) years of age or older and must execute liability/publicity releases prior to issuance of tickets and/or admission passes. Sponsor is not responsible for lost, mutilated or stolen Event admission passes/tickets. Winners and guests must follow any applicable COVID protocols that may be in place at time of Event. The names of individuals, companies, products and/or logos are used for identification purposes only and are the intellectual property of their respective owners. The mention of any entity, or the inclusion of a product or service as a prize, does not imply any association with or endorsement by such entity or the manufacturer or distributor of such product or service and, except as otherwise indicated, no association or endorsement is intended or should be inferred. Sponsor is not responsible if the Event is delayed, postponed or cancelled for any reason, or for issues arising from the operation and management of the Event, in which event the prize is forfeited in its entirety and no substitution will be provided except as in Sponsor's sole discretion. In the event the Event is cancelled or postponed, Sponsor will have no obligation to award compensation in lieu thereof. Failure to attend Event does not relieve winner of his/her tax obligations associated with acceptance of a prize, as outlined elsewhere in these Official Rules.

Prize General Conditions. Prize(s) subject to availability. Each prize winner is solely responsible for all other expenses not specifically set forth herein, including but not limited to surcharges, service charges, shipping and handling, taxes, and other incidentals and items of a personal nature. Prizes consist of only the items specifically listed as part of the prize. Prize details not specified herein shall be determined solely by Sponsor. Prize(s) are awarded "as is" with no warranty or guarantee, either express or implied. No alcohol is awarded in any prize. Resale of prize(s) is prohibited. Sponsor is not responsible for lost, stolen or mutilated prizes, in which event the prize is forfeited in its entirety and Sponsor will have no obligation to award compensation in lieu thereof and no substitution will be provided except as in Sponsor's sole discretion. Actual value of prize(s) may vary. Sponsor is not responsible for and winner will not receive any difference between the actual value and ARV of a prize. In the event that an insufficient number of eligible entries are received to award all available prizes, Sponsor is not obligated to award remaining prizes and no additional random drawings will take place. No transfer, assignment, substitution or cash equivalent for any prize will be permitted, except at the sole discretion of the Sponsor due to prize unavailability for any reason.  Sponsor reserves the right to substitute a prize for one of equal or greater value if the designated prize should become unavailable for any reason, and Sponsor's obligation to the winner(s) will be fulfilled and no other compensation will be provided. In the event of prize unavailability, if the Sweepstakes becomes impossible or commercially unreasonable to administrate, or any other reason in Sponsor's sole discretion, Sponsor reserves the right to cancel, postpone, or modify (in whole or in part) the Sweepstakes. Winner(s) are responsible for all federal, state and local taxes and fees associated with prize award, receipt and/or use. Failure to pick-up or use prize does not relieve winner of his/her tax obligations associated with acceptance of a prize. Sweepstakes winnings will be reported to the Internal Revenue Service and winner can expect to receive a 1099 tax form for prizes which total more than $600.00 for the year. Limit one (1) prize per person/household.

7. Release: In exchange for the right to participate in the Sweepstakes, the entrants, the winner(s) and, if applicable, winner(s)' travel companions, agree to release and hold harmless Sponsor, Administrator and their respective parent companies, subsidiaries, affiliates, divisions, suppliers, distributors, advertising/promotion agencies, and prize suppliers, Event organizer, venue owner, and each such company's officers, directors, employees and agents (collectively, the "Released Parties") from and against any claim or cause of action, including, but not limited to, personal injury, death, or damage to or loss of property, arising out of participation in or in connection with the Sweepstakes or receipt or use or misuse of any prize. Released Parties are not responsible for technical, hardware, network connections or incomplete or delayed computer transmissions, regardless of cause. In the event there is a discrepancy or inconsistency between disclosures or other statements contained in any Sweepstakes materials and the terms and conditions of the Official Rules, the English version of the Official Rules shall prevail, govern and control. All entrants understand and agree that all rights under Section 1542 of the Civil Code of California ("Section 1542") and any similar law of any state, territory, or country that may be applicable with respect to the foregoing release are hereby expressly and forever waived. All participating entrants acknowledge that Section 1542 provides that: "A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS THAT THE CREDITOR OR RELEASING PARTY DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE AND THAT, IF KNOWN BY HIM OR HER, WOULD HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR OR RELEASED PARTY." The releases hereunder are intended to apply to all claims not known or suspected to exist with the intent of waiving the effect of laws requiring the intent to release future unknown claims.

8. Publicity: Except where prohibited, participation in the Sweepstakes constitutes each winner's consent to Sponsor's and its agents' use of each winner's name, likeness, photograph, voice, quotes, statements, opinions, biographical information and/or hometown and state for promotional purposes in any media now known or hereinafter invented, worldwide, without further payment or consideration.

9. General Conditions: Sponsor reserves the right to cancel, suspend and/or modify the Sweepstakes, or any part of it, if any fraud, technical failures or any other factor beyond Sponsor's reasonable control impairs the integrity or proper functioning of the Sweepstakes, as determined by Sponsor in its sole discretion. Sponsor reserves the right, in its sole discretion, to disqualify any individual it finds to be tampering with the entry process or the operation of the Sweepstakes or to be acting in violation of these Official Rules, any other promotion or applicable law, or in an unsportsmanlike or disruptive manner. Any attempt by any person to deliberately undermine the legitimate operation of the Sweepstakes may be a violation of criminal and civil law, and, should such an attempt be made, Sponsor reserves the right to seek damages from any such person to the fullest extent permitted by law. Sponsor's failure to enforce any term of these Official Rules shall not constitute a waiver of that provision. By entering the Sweepstakes and accepting a prize, each winner agrees to maintain his/her behavior in accordance with all applicable laws and generally-accepted social practices in connection with participation in the Sweepstakes or prize-related activity.  Each winner understands and agrees that Sponsor or the prize provider have the right, in their sole discretion, to disqualify and remove the winner (and/or his/her guest, if applicable) from any activity at any time if the winner's (and/or his/her guest's) behavior at any point (i) is uncooperative or disruptive; (ii) annoys, threatens, or harasses any other person; (iii) may or does cause damage to person, property, or the reputation of Sponsor or a prize provider; or (iv) otherwise violates the policies of the prize provider; and, in such a case, the winner will forfeit all remaining elements of the prize and still be solely responsible for all taxes and other expenses related to the prize.  In the event a Prize winner or his/her guest/travel companions consume alcoholic beverages (none will be provided by Sponsor) while participating in any Prize-related activities, he/she does so at his/her own discretion and agree to hold Released Parties harmless from any subsequent damages or third-party claims arising out of or related to such consumption.

10. Limitations of Liability: The Released Parties are not responsible for: (a) any incorrect or inaccurate information, whether caused by entrants, printing errors or by any of the equipment or programming associated with or utilized in the Sweepstakes; (b) technical failures of any kind, including, but not limited to malfunctions, interruptions, or disconnections in phone lines or network hardware or software whether originating with entrant, Sponsor, or any third party; (c) unauthorized human intervention in any part of the entry process or the Sweepstakes; (d) technical or human error which may occur in the administration of the Sweepstakes or the processing of entries; (e) late, lost, undeliverable, misdirected, illegible, damaged, incomplete, incorrect, stolen, or postage due entries/mail; or (f) any injury or damage to persons or property which may be caused, directly or indirectly, in whole or in part, from entrant's participation in the Sweepstakes or receipt or use or misuse of any prize. If for any reason an entrant's entry is confirmed to have been erroneously deleted, lost, or otherwise destroyed or corrupted, entrant's sole remedy is another entry in the Sweepstakes, unless it is not possible to award another entry due to the date of discontinuance for any or all of the prizes offered herein. In the event of a discontinuance of the Sweepstakes, or any part of it, for any reason, Sponsor, in its sole discretion, may elect to hold a random drawing from among all eligible entries received up to the date of discontinuance, and in no event will more than the stated number of prizes be awarded. In the event that production, technical, seeding, programming or any other reasons cause more than the stated number of prizes as set forth in these Official Rules to be available and/or claimed, Sponsor reserves the right to award only the stated number of prizes by a random drawing among all legitimate, un-awarded, eligible prize claims.

11. Disputes: THIS SWEEPSTAKES IS GOVERNED BY THE LAWS OF THE UNITED STATES AND THE STATE OF NEW YORK, WITHOUT RESPECT TO CONFLICT OF LAW DOCTRINES. As a condition of participating in this Sweepstakes and/or accepting an awarded prize, each entrant agrees that any and all disputes that cannot be resolved between the parties and causes of action arising out of or connected with this Sweepstakes shall be resolved individually, without resort to any form of class action, exclusively before any federal courts in the Western District of New York or, if such courts do not have subject matter jurisdiction, state courts in Monroe County, New York. Further, in any such dispute, under no circumstances will entrant be permitted to obtain awards for and hereby waives all rights to claim punitive, incidental, or consequential damages, including reasonable attorneys' fees, other than entrant's actual out-of-pocket expenses (i.e., evidenced costs associated with entering this Sweepstakes), and entrant further waives all rights to have damages multiplied or increased.

12. Entrant's Personal Information: Information collected from entrants is subject to Sponsor's privacy policy, available at www.cbrands.com/privacy-policy ("Privacy Policy"). By entering this Sweepstakes, each entrant confirms that he/she has read, agrees to and accepts Sponsor's Privacy Policy.

13. Winner List: To receive a winner list, send a self-addressed, stamped envelope by 3/16/2026 to Optivate Agency, 4403 Oleander Dr., Ste. C #251, Wilmington, NC 28403.

Drink responsibly. Corona Premier® Beer. Imported by Crown Imports, Chicago, IL`;



// All promotions data - 12 items total
import coronaLogo from '../assets/logo-master-corona-white.webp';
import pacificoLogo from '../assets/logo-pacifico-color.webp';
import modeloLogo from '../assets/logo-modelo.webp';

export const allPromotions = [
    {
        id: 1,
        title: "Premier Serve 2026 Sweepstakes",
        description: "Enter for Your Chance to Win",
        brand: "corona",
        fromDate: "12/15/2025",
        toDate: "02/11/2026",
        image: "https://cdn.shortpixel.ai/spai/ret_img/cbisweeps.com/wp-content/uploads/2025/12/FF—2796-Corona-Premier-x-BNP-2026-hero.webp?t=1766467401",
        link: "https://cbisweeps.com/premierserve2026sweepstakes/",
        brandLogo: coronaLogo,
        register: "Corona Extra®"
    },
    {
        id: 2,
        title: "The Pacifico Winter Gear Sweepstakes",
        description: "Enter for Your Chance to Win ",
        brand: "pacifico",
        fromDate: "12/01/2025",
        toDate: "01/31/2026",
        image: "https://cdn.shortpixel.ai/spai/ret_img/cbisweeps.com/wp-content/uploads/2025/11/FF—2800-WBU-Pacifico-Winter-Gear-Sweeps-hero.webp",
        link: "https://cbisweeps.com/pacwintergear/",
        brandLogo: pacificoLogo,
        register: "Pacifico Clara®"
    },
    {
        id: 3,
        title: "Corona Premier Josh Allen Autographed Football",
        description: "Enter for Your Chance to Win",
        brand: "corona",
        fromDate: "12/01/2025",
        toDate: "01/31/2026",
        image: "https://cdn.shortpixel.ai/spai/ret_img/cbisweeps.com/wp-content/uploads/2025/11/FF—2803-Corona-Premier-Josh-Allen-Autographed-Football-Sweeps-hero.webp",
        link: "https://cbisweeps.com/coronajoshallenfootball/",
        brandLogo: coronaLogo,
        register: "Corona Premier®"
    },
    {
        id: 4,
        title: "Coronita Cooler Party",
        description: "Enter for Your Chance to Win",
        brand: "corona",
        fromDate: "11/17/2025",
        toDate: "02/28/2026",
        image: "https://cdn.shortpixel.ai/spai/ret_img/cbisweeps.com/wp-content/uploads/2025/11/FF—2808-Coronita-Cooler-Party-hero.webp",
        link: "https://cbisweeps.com/coronitacoolerparty/",
        brandLogo: coronaLogo,
        register: "Coronita Extra®"
    },
    {
        id: 5,
        title: "Corona x Tampa Bay Lightning Sweepstakes",
        description: "Enter for Your Chance to Win",
        brand: "corona",
        fromDate: "11/01/2025",
        toDate: "03/21/2026",
        image: "https://cdn.shortpixel.ai/spai/ret_img/cbisweeps.com/wp-content/uploads/2025/10/FF—2780-Corona-x-Tampa-Bay-Lightning-hero.webp",
        link: "https://cbisweeps.com/coronalightning2025/",
        brandLogo: coronaLogo,
        register: "Corona Extra®"
    },
    {
        id: 6,
        title: "Modelo Holiday",
        description: "Enter for Your Chance to Win",
        brand: "modelo",
        fromDate: "10/27/2025",
        toDate: "01/06/2026",
        image: "https://cdn.shortpixel.ai/spai/ret_img/cbisweeps.com/wp-content/uploads/2025/10/FF—2758-Modelo-Holiday-hero.webp",
        link: "https://cbisweeps.com/modeloholiday/",
        brandLogo: modeloLogo,
        register: "Modelo Especial®"
    },
    {
        id: 7,
        title: "Modelo Football",
        description: "Enter for Your Chance to Win",
        brand: "modelo",
        fromDate: "10/27/2025",
        toDate: "01/06/2026",
        image: "https://cdn.shortpixel.ai/spai/ret_img/cbisweeps.com/wp-content/uploads/2025/10/FF—2758-Modelo-Football-hero.webp",
        link: "https://cbisweeps.com/modelofootball/",
        brandLogo: modeloLogo,
        register: "Modelo Especial®"
    },
    {
        id: 8,
        title: "Pacifico Holiday",
        description: "Enter for Your Chance to Win",
        brand: "pacifico",
        fromDate: "10/27/2025",
        toDate: "01/06/2026",
        image: "https://cdn.shortpixel.ai/spai/ret_img/cbisweeps.com/wp-content/uploads/2025/10/FF—2758-Pacifico-hero.webp",
        link: "https://cbisweeps.com/pacificoholiday/",
        brandLogo: pacificoLogo,
        register: "Pacifico Clara®"
    },
    {
        id: 9,
        title: "Corona Holiday",
        description: "Enter for Your Chance to Win",
        brand: "corona",
        fromDate: "10/27/2025",
        toDate: "01/06/2026",
        image: "https://cdn.shortpixel.ai/spai/ret_img/cbisweeps.com/wp-content/uploads/2025/10/FF—2758-Corona-hero.webp",
        link: "https://cbisweeps.com/coronaholiday/",
        brandLogo: coronaLogo,
        register: "Corona Extra®"
    },
    {
        id: 10,
        title: "Pacifico x Los Angeles Chargers Jersey Sweepstakes",
        description: "Enter for Your Chance to Win",
        brand: "pacifico",
        fromDate: "08/15/2025",
        toDate: "12/31/2025",
        image: "https://cdn.shortpixel.ai/spai/ret_img/cbisweeps.com/wp-content/uploads/2025/08/FF—2726-Pacifico-x-Chargers-Custom-Jersey-Sweepstakes-hero.webp",
        link: "https://cbisweeps.com/2025pacificolacjerseysweeps/",
        brandLogo: pacificoLogo,
        register: "Pacifico Clara®"
    },
    {
        id: 11,
        title: "Corona® Premier Golf Sweepstakes",
        description: "Enter for Your Chance to Win",
        brand: "corona",
        fromDate: "08/01/2025",
        toDate: "03/02/2026",
        image: "https://cdn.shortpixel.ai/spai/ret_img/cbisweeps.com/wp-content/uploads/2025/07/FF—2711-Corona-Premier-x-Golf-hero.webp",
        link: "https://cbisweeps.com/premier-golf-2025/",
        brandLogo: coronaLogo,
        register: "Corona Premier®"
    },
    {
        id: 12,
        title: "Discover Your Pacifico Adventure",
        description: "Enter for Your Chance to Win",
        brand: "pacifico",
        fromDate: "03/03/2025",
        toDate: "12/29/2025",
        image: "https://cdn.shortpixel.ai/spai/ret_img/cbisweeps.com/wp-content/uploads/2025/02/FF—2585-Pacifico-x-Adventure-2025-hero.webp",
        link: "https://cbisweeps.com/pacificoadventure2025/",
        brandLogo: pacificoLogo,
        register: "Pacifico Clara®"
    }
];


// FAQ Items    
export const faqItems = [
    {
        id: 1,
        question: "Why is a copy of my ID needed?",
        answer: "The official rules state that you must be 18 years of age or older to win if the sponsor company is a non-alcoholic beverage brand and you must be 21 years of age or older if the sponsor company is an alcoholic beverage brand. We must receive a copy of your state-issued identification with your full name, date of birth, and state of residence clearly visible. All other information can be blurred out."
    },
    {
        id: 2,
        question: "What if I do not live in an eligible state?",
        answer: "A winner must reside in a state identified in the official rules. If you do not reside in a state listed in the official rules you are not eligible to claim a prize.\n\n"
    },
    {
        id: 3,
        question: "Why is an affidavit needed?",
        answer: "The Internal Revenue Service (IRS) guidelines state that we must report winnings for all prizes valued at $600 or higher. Affidavits are used to collect the information required to complete a 1099 tax form. We will send your 1099 tax form with the value of your prize to you at the end of the year. The prize is forfeited if you do not complete an affidavit."
    },
    {
        id: 4,
        question: "Will I receive a tracking number for my prize?",
        answer: "Yes, we will send you a tracking number for your prize when it becomes available from the shipping company."
    },
    {
        id: 5,
        question: "Why haven't I received my prize?",
        answer: "Prizes can be delayed due to production delays and shipping issues."
    },
    {
        id: 6,
        question: "Is there a cash-out option for my prize?",
        answer: "Prizes do not have a cash-out option. Any changes to the prize are at the sole discretion of the sponsor company."
    }
];